### ISSUE TITLE
Articulated vehicles steering camera-rotation

### ISSUE THREAD

**Issue by Vanquish081** [DeckerMMIV/FarmSim_Mod_QuickCamera#17]
Hi, the version FS15 QuickCamera included slow motion with articulated vehicles, isn't this feature in FS17?

**Comment by DeckerMMIV** [comment]
Yeah, the 'articulated-vehicles outside camera fix' and the 'in-cabin panning camera' I did not include with the FS17 version of the mod, due to the many small script changes in FS17 which I have yet to figure out.

I will look into adding them again. Though I am not completely satisfied with the 'panning camera' feature, as it is a tiny bit "jerky" at times.

**Comment by DeckerMMIV** [comment]
Its been a (_very long_) while, but finally I have looked into the articulated vehicle steering camera-rotation fix.
Please take a look at the version 1.2.0.28 (or higher) of the mod.

I have set some mod-default camera-rotation values for the following vehicles;
- Liebherr L 538
- New Holland T9
- JCB TM320S/435S
- Ponsse ScorpionKing/Buffalo
- Sampo Rosenlew HR46X

Currently there is only a console-command `modQuickCameraSteeringRotSpeed` for changing the rotation speed of the current active camera when in a vehicle.

A user configuration-file will be saved to `/modsSettings/QuickCamera_Config.XML` when setting a new rotation-value using the `modQuickCameraSteeringRotSpeed <new_decimal_value>`.

**Comment by Vanquish081** [comment]
Hi, I tested it and is more smooth, difference is noted, thanks for your job :+1:
