### ISSUE TITLE
CZMOD_CLAAS_Xerion_4500 & experimentals QuickCamera

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [DeckerMMIV/FarmSim_Mod_QuickCamera#3]
I use these two mods. When I sit down in CZMOD_CLAAS_Xerion_4500 get an error and block games.
Error: Running LUA method 'update'.
D:\FARMING_SIMULATOR\mods15//QuickCamera_experimentals/SteeringRotateCamera.lua:74: attempt to perform arithmetic on field 'mod_previous_rotatedTime' (a nil value)

**Comment by DeckerMMIV** [comment]
If that CZMOD_CLAAS_Xerion_4500 is either not using the default 'Drivable' specialization, or is redefining it, then that may be the cause of the error.

The reason is, that my SteeringRotateCamera.LUA script modifies the `Drivable.updateVehiclePhysics()` method, so if the mod is in some way not using 'default scripts', then problems will occur.

Do you have a download-link for that mod, so I can test it myself?

**Comment by Gonimy-Vetrom** [comment]
https://drive.google.com/file/d/0B_zrlMUSl3roRmZMTDZvVUd1Qm8/view?usp=sharing

**Comment by DeckerMMIV** [comment]
Hmm. First impression, by studying the content of the ZIP.
That mod contains a **compiled** `BeifahrerV2.lua` by Alex2009.
Since it is not human-readable LUA script code, I will remove that nonsense-and-closed-source bigot file, before even attempting to test it in-game.
(*Yes, I am so annoyed that Alex2009 makes compiled scripts for his mods, because he probably don't want others to "copy" from them.*)

**Comment by DeckerMMIV** [comment]
Hmm. After removing the **compiled** `BeifahrerV2.lua` specialization and tested in-game, the error in SteeringRotateCamera.LUA still occurs.
I will investigate further.

**Comment by DeckerMMIV** [comment]
It looks like it is caused by the 1st camera is the "isInside" one.
All of the vehicles I have tested, have 1st camera as the "3rd person / outside".
So apparently the `Drivable.updateVehiclePhysics()` is not called as early as I had hoped.
Attempting a fix.

**Comment by DeckerMMIV** [comment]
Fixed.. I hope.

Also: Please be aware of, that when "rotating the cabin / change driving direction", then the camera-panning/rotation becomes opposite of what it is supposed. - That is a different problem which I need to figure out how to solve.

**Comment by Gonimy-Vetrom** [comment]
Thank you! Now works.
