### ISSUE TITLE
Any fixed rotations don't work

### ISSUE THREAD

**Issue by nicolafarina** [DeckerMMIV/FarmSim_Mod_QuickCamera#41]
Hi there,

this is a fantastic idea for a mod but, in FS22, I can't make fixed rotations (45/90/180°) work consistently. I tried unbinding any keyboard or controllers keys but when I try to look at 90° right (f.e.), the command sometimes works only.

Peek works flawlessly, like continuous rotation (long pressing the same keys for fixed rotations).

Any help?

**Comment by DeckerMMIV** [comment]
Maybe conflict with another mod that also attempts to control vehicle camera's rotation?

Or maybe if you are using a combination of keyboard, mouse, gamepad/wheel and switching between those input devices ad-hoc, that my mod's script gets confused due to the vanilla game's base scripts are changing the input-mode? - That is something I  would have difficulties with figuring out, as I am a 'only keyboard+mouse' player and still only use keyboard-keys for frontloader-tools raise/lower/... actions.

Or if you are using modifier keys (SHIFT, CTRL or ALT) along with other key to press for the action, then try to observe if your fingers are "too quick" with pressing the specific sequence of the keys/buttons. Make sure that the modifier key(s) is fully pressed before the last key/button is pressed-and-quick-released.

I request that you experiment with a new savegame, where this single mod is the ONLY ONE being activated. - Then use only the game's vanilla vehicles and see if you can reliably reproduce the problem, first by using only keyboard keys.

If you are also using a steering-wheel's buttons and/or gamepad's buttons, then try to examine if there might be actual physical issues with the buttons - i.e. the micro-switch(es) might need cleaning.

**Comment by nicolafarina** [comment]
I supposed was something related to other mods. Anyway, I'm now using another mod with similar functionalities.

Thanks for replying, though.
